ATH_UBB/Areas/Users/Controllers/ReservationsController.cs
using ATH_UBB.Data;
using ATH_UBB.Model;
using ATH_UBB.Models;
using AutoMapper;
using IRepositoryService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RepositoryService;

namespace ATH_UBB.Areas.Users.Controllers
{
    [Area("Users")]
    [Authorize(Roles = "User")]
    public class ReservationsController : Controller
    {
        private readonly IRepositoryService<Reservation> _reservationRepository;
        private readonly IRepositoryService<Vehicle> _vehicleRepository;
        private readonly IMapper _mapper;
        public ReservationsController(ApplicationDbContext context, IMapper mapper)
        {
            _reservationRepository = new RepositoryService<Reservation>(context);
            _vehicleRepository = new RepositoryService<Vehicle>(context);
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Guid id, [Bind("StartDate,EndDate,User")] ReservationViewModel reservation)
        {
            if (ModelState.IsValid)
            {
                var vehicle = _vehicleRepository.GetSingle(id);
                if (vehicle.IsReserved)
                {
                    reservation.Id = Guid.NewGuid();
                    reservation.StartDay = DateTime.Now;
                    reservation.VehicleId = id;
                    _reservationRepository.Add(_mapper.Map<Reservation>(reservation));
                    _reservationRepository.Save();
                    vehicle.IsReserved = false;
                    _vehicleRepository.Edit(vehicle);
                    _vehicleRepository.Save();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(reservation);
        }

    }
}

ATH_UBB/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ATH_UBB.Data;
using ATH_UBB.Model;
using IRepositoryService;
using RepositoryService;
using AutoMapper;
using ATH_UBB.Models;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;

namespace ATH_UBB.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly IRepositoryService<Vehicle> _context;
        private readonly IMapper _mapper;
        private readonly IValidator<VehicleDetailViewModel> _validator;
        public VehiclesController(ApplicationDbContext context, IMapper mapper, IValidator<VehicleDetailViewModel> validator)
        {
            _context = new RepositoryService<Vehicle>(context);

            //_context.Add(new Vehicle()
            //{
            //    Id = Guid.NewGuid(),
            //    Name = "costam",
            //    Brand = "makita",
            //    Description = " super rower",
            //    Price = 999,
            //    IsReserved = false,
            //    Type = new VehicleType() { Id = Guid.NewGuid(), TypeName = "rower"},
            //    RentalPoint = new RentalPoint() { Id = Guid.NewGuid(), Adres = "Mickiewicza 1", City="Kety"}
                

            //});
            _mapper = mapper;
            _validator = validator;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            var VehicleIndex = _context.GetAllRecords();
            List<VehicleItemViewModel> vehiclesViewModelsIndex = new List<VehicleItemViewModel>();
            foreach (var item in VehicleIndex)
            {
                vehiclesViewModelsIndex.Add(_mapper.Map<VehicleItemViewModel>(item));
            }

            return View(vehiclesViewModelsIndex);
        }

        // GET: Vehicles/Details/5
        
        public async Task<IActionResult> Details(Guid? id)
        {
            if ( _context.GetAllRecords() == null)
            {
                return NotFound();
            }

            var vehicle = await _context.GetAllRecords()
                .Include(v => v.Reserv)
                .Include(v => v.Type)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<VehicleDetailViewModel>(vehicle));
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,price,brand,model,localization,description,isAvailable")] VehicleDetailViewModel vehicle)
        {

            ValidationResult result = await _validator.ValidateAsync(vehicle);

            if (result.IsValid)
            {
                vehicle.Id = Guid.NewGuid();
                _context.Add(_mapper.Map<Vehicle>(vehicle));
                _context.Save();
                
                return RedirectToAction(nameof(Index));

            }
            result.Errors.ForEach(error => ModelState.AddModelError(error.PropertyName, error.ErrorMessage));
            return View(vehicle);

            //ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Id", vehicle.ReservationId);
            //ViewData["TypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id", vehicle.TypeId);

        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            if ( _context.GetAllRecords() == null)
            {
                return NotFound();
            }
            var vehicle = _context.GetAllRecords()
                .Include(v => v.Reserv)
                .Include(v => v.Type)
                .FirstOrDefaultAsync(m => m.Id == id);
            //var vehicle =  _context.GetSingle(id).;
            if (vehicle == null)
            {
                return NotFound();
            }
            //ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Id", vehicle.ReservationId);
            //ViewData["TypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id", vehicle.TypeId);
            return View(_mapper.Map<VehicleDetailViewModel>(vehicle));
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,price,brand,model,localization,description,isAvailable")] VehicleDetailViewModel vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Edit(_mapper.Map<Vehicle>(vehicle));
                    _context.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Id", vehicle.ReservationId);
            //ViewData["TypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id", vehicle.TypeId);
            return View(_mapper.Map<Vehicle>(vehicle));
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            if ( _context.GetAllRecords() == null)
            {
                return NotFound();
            }

            var vehicle =await _context.GetAllRecords()
                .Include(v => v.Reserv)
                .Include(v => v.Type)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<VehicleDetailViewModel>(vehicle));
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.GetAllRecords() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Vehicles'  is null.");
            }
            var vehicle = _context.GetAllRecords()
                .Include(v => v.Reserv)
                .Include(v => v.Type)
                .FirstOrDefault(m => m.Id == id);
            if (vehicle != null)
            {
                _context.Delete(vehicle);
            }
            
            _context.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(Guid id)
        {
          return (_context.GetAllRecords()?.Any(e => e.Id == id)).GetValueOrDefault();
        }

      
        public IActionResult EndReservation(Guid id)
        {
           
            var vehicle = _context.GetSingle(id);                
            vehicle.IsReserved = true;
            _context.Edit(vehicle);
            _context.Save();    
            return Redirect("/Vehicles");
        }
    }
}

ATH_UBB/Views/Vehicles/Create.cshtml
@model ATH_UBB.Models.VehicleDetailViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>VehicleDetailViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brand" class="control-label"></label>
                <input asp-for="brand" class="form-control" />
                <span asp-validation-for="brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="model" class="control-label"></label>
                <input asp-for="model" class="form-control" />
                <span asp-validation-for="model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="localization" class="control-label"></label>
                <input asp-for="localization" class="form-control" />
                <span asp-validation-for="localization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsReserved" /> @Html.DisplayNameFor(model => model.IsReserved)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ATH_UBB/Views/Vehicles/Delete.cshtml
@model ATH_UBB.Models.VehicleDetailViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleDetailViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.localization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.localization)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsReserved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsReserved)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ATH_UBB/Views/Vehicles/Details.cshtml
@model ATH_UBB.Models.VehicleDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VehicleDetailViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.localization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.localization)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsReserved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsReserved)
        </dd>
    </dl>
</div>
<div>
    @if (Model.IsReserved)
    {
        <a asp-area="Users" asp-controller="Reservations" asp-action="Create" asp-route-id="@Model?.Id">Zarezerwuj</a> <span>|</span>
    }
    @if (Model.IsReserved == false)
    {
        <form method="post" action="@Url.Action("EndReservation","Vehicles")">
            <input type="hidden" name="id" value="@Model.Id" />
            <button id="delete" type="submit">Usuń Reserwacje</button>
        </form>  
    }
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ATH_UBB/Views/Vehicles/Edit.cshtml
@model ATH_UBB.Models.VehicleDetailViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>VehicleDetailViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brand" class="control-label"></label>
                <input asp-for="brand" class="form-control" />
                <span asp-validation-for="brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="model" class="control-label"></label>
                <input asp-for="model" class="form-control" />
                <span asp-validation-for="model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="localization" class="control-label"></label>
                <input asp-for="localization" class="form-control" />
                <span asp-validation-for="localization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsReserved" /> @Html.DisplayNameFor(model => model.IsReserved)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ATH_UBB/Views/Vehicles/Index.cshtml
@model IEnumerable<ATH_UBB.Models.VehicleItemViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.localization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsReserved)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.localization)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.IsReserved)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>